### PR TITLE
Adds the `craft` and `craftOne` methods.

### PR DESCRIPTION
**Pull request by lukeraymonddowning**
I've been using Poser extensively in a big project, and using it to create all models, not just complex ones. Often, I just want to quickly build a model or collection or models and return the result.

This PR adds the `::craft` and `::craftOne` static methods, which can be used instead of `::new` or `::times` to do exactly as described above. You may pass in attributes to the methods, and they  will be used as you'd expect. This is basically short hand for `XyzFactory::new()->withAttributes(['name' => 'value'])->create()`. The previous statement could now be rewritten as `XyzFactory::craft(['name' => 'value])`.

### CODE REVIEW

**Comment by AlanHolmes** [comment]
I like this idea 😄  

but, just as a though, rather than have 2 methods, how about just `craft` but inverse the params, so its `craft($attributes, $count = 1)` (similar to `factory(class, count)`)?

**Comment by lukeraymonddowning** [comment]
Great input @AlanHolmes, I'll alter accordingly

**Comment by lukeraymonddowning** [comment]
@AlanHolmes I've now finally gotten around to updating this. There is just a single `craft` method. Not as simple as you might think, because we support multiple attributes being passed in. I've had to do a little movie magic. The count may be omitted or passed as the first or last parameter to the `craft` method.

Let me know your thoughts and any changes you'd suggest.

**Review by AlanHolmes — COMMENTED** [review]
Looks good to me 👍

**Pull request merged**
