### PR TITLE
First pass at cleanup of Factory.php

### PR DESCRIPTION
**Pull request by lukeraymonddowning**
Renamed methods where appropriate, simplified logic and improved readability.

- No public method names have been changed, and the functionality remains identical.
- Some protected and private method names have changed, where appropriate, to better reflect the action that the method is taking

### CODE REVIEW

**Comment by lukeraymonddowning** [comment]
@AlanHolmes, @andreich1980 are you guys able to look through this for me? Changes to protected methods will mean a major version increment, but I personally feel it is worth it. I've added an `UPGRADE.md` file, but long and short of it is that if you haven't overridden any protected properties or methods, you don't need to make any changes.

`Factory.php` has been cleaned up quite drastically, which I wanted to tackle before moving any further forwards with the project. Let me know your thoughts on the changes, and suggest any other changes you think would be valuable at this time.

Thanks guys.

**Comment by AlanHolmes** [comment]
All changes seem ok to me, and files are generating fine, so all good 👍 

My only thought right now, is that maybe all `private` functions should be `protected`.

Simply due to the nature of this setup, users are always going to be extending this base class, and although they shouldn't need to, there might be the chance that they need to override one of the methods for a very specific use case, but if that method calls a private function, then it will error for them, or they would also have to override that private method.

It also means if they add a custom method that might want to utilise any of these functions they can't without overriding them.

I understand why they are used, but because of the reasons above I personally never use private methods/variables, but thats just my opinion 😄

**Comment by AlanHolmes** [comment]
Also, whilst this cleanup is happening, not sure what you think about upgrading the standards to psr-12, since as of 2019-08-10 PSR-2 has been marked as deprecated:
https://www.php-fig.org/psr/psr-2/?

**Comment by lukeraymonddowning** [comment]
> All changes seem ok to me, and files are generating fine, so all good 👍
> 
> My only thought right now, is that maybe all `private` functions should be `protected`.
> 
> Simply due to the nature of this setup, users are always going to be extending this base class, and although they shouldn't need to, there might be the chance that they need to override one of the methods for a very specific use case, but if that method calls a private function, then it will error for them, or they would also have to override that private method.
> 
> It also means if they add a custom method that might want to utilise any of these functions they can't without overriding them.
> 
> I understand why they are used, but because of the reasons above I personally never use private methods/variables, but thats just my opinion 😄

@AlanHolmes, I think my initial thought on the private methods was more 'they don't need to know how this happens'. For the initial scope of the idea, that worked well. However, as this has been trialed and used by myself and others, and continues to grow further, I think you're right.

I've elected to remove 2 private methods, instead choosing to inline them. They were both only used in one place and didn't really add anything. The other `private` methods have been made `protected`, and looking through them, I can see why one would want to convert/extend the functionality of those particular functions given a special case. I would like to try my level best to make sure that Poser covers those use cases/is smart enough to handle them, but in all honesty Poser is for the 80% case. The ability to extend as desired would cover the other 20%.

I may go through and document all of the protected methods before merging this in.

**Comment by AlanHolmes** [comment]
Yeah their use makes sense in certain cases, just saying what I have found (mainly from working on large legacy apps) that private methods tend to be more of a hindrance 😄

**Comment by andreich1980** [comment]
Nice job guys 👍🏻 Sorry I'm late to the party :D Was on a short vacation.

**Comment by lukeraymonddowning** [comment]
> Nice job guys 👍🏻 Sorry I'm late to the party :D Was on a short vacation.

@andreich1980 sorry matey, I took your thumbs up as the go ahead 🤣 hope you had a nice time 👍👍👍

**Pull request merged**
