### PR TITLE
More tests

### PR DESCRIPTION
**Pull request by andreich1980**
New tests for:
-  `with<Relationship>()`/`for<Relationship>()` 
- `as()`/`state()` and `states()`
- `CreatePoserFactory` command.
  - Here I need an advise: I run `make:poser` command during the test and it creates a brand new factory. I could remove it in the `tearDown` method but I decided to leave it and delete in `setUp`, before the test is starting, instead. And because of that I had to add the path to `.gitignore`. What do you think about that? If you would use `Storage` instead of `File` - it could be faked then. But right now it is like this. Give me your thoughts and I'll fix it if needed.

Updated some typo-s in `README.md`
- Here I have a question. Can `ModelNotBuiltException` ever happend after you added `Automated 'create' functionality`? I couldn't make it thrown. If this is still a thing - tell me how to reproduce it and I'll add a test for that. Otherwise this you could remove the exception from the `Readme` or update the section.

### CODE REVIEW

**Comment by AlanHolmes** [comment]
> I could remove it in the tearDown method but I decided to leave it and delete in setUp, before the test is starting, instead. And because of that I had to add the path to .gitignore. What do you think about that?

I wouldn't have thought that this would be an issue really, but I would do it where they are stored in something like `test/storage`, and rather than adding that to the main `.gitignore` you include a separate `.gitignore` in that folder to exclude any files, but to keep the folder (kind of like how laravel does with the `storage/framework/testing` folder that it uses if you are using `Storage::fake()`.

**Comment by andreich1980** [comment]
I'd put it somewhere in the `test/storage` but the paths  are related to namespaces. 
Thanks for the feedback, I'll try to figure it out.

**Comment by andreich1980** [comment]
@AlanHolmes I took a dive in the `CreatePoserFactory.php` it uses `base_path` to get the destination directory for poser factories.
I faked it like that `$this->app->setBasePath('storage');` but when I tried to call `make:poser` command with `--model` or `--factory` options I got an error `ErrorException : file_get_contents(storage/composer.json): failed to open stream: No such file or directory` when `getNamespace()` is used because it looks for `composer.json` via the Laravel helper functinon `base_path()`
Any ideas?

**Comment by AlanHolmes** [comment]
@andreich1980 hmm, yeah I get it would do something like that with changing basepath.

The only other thing you can do, since it seems to be using base path + namespace is change the namespace for the test into a folder that is designed just for test files.

**Comment by AlanHolmes** [comment]
@andreich1980 if you still have no luck, if you push what you have so far as a WIP commit, I will try and take a look when I get chance

**Comment by andreich1980** [comment]
Thanks, Alan. I'll try to figure it out myself and will push WIP for you otherwise.

**Comment by lukeraymonddowning** [comment]
Hi @andreich1980 @AlanHolmes 

Sorry for the delay on this. I wasn't available yesterday. I appreciate all your efforts 👍 

> * Here I have a question. Can `ModelNotBuiltException` ever happend after you added `Automated 'create' functionality`? I couldn't make it thrown. If this is still a thing - tell me how to reproduce it and I'll add a test for that. Otherwise this you could remove the exception from the `Readme` or update the section.

I think you're right with this. I'll create a new branch and fix. I think I'm going to include the `ForwardsMethodCalls` trait and go that way. Then we have a built in error message from Laravel.

**Comment by andreich1980** [comment]
I managed to move files created during the testing into `tests/storage` by setting `base_path()` to this folder and creating a *fake* `composer.json` in there, because `getNamespace()` needs `composer.json` in the `base_path()`.

The only remaining problem is when I try to create a poser factory with `--model="\App\Models\User"` option to attach the factory to a model with different namespace .
It makes weird namespaces like that:
```php
/**
  * @method /*shortened*/|\Lukeraymonddowning\Poser\App\Models\User[]|\Lukeraymonddowning\Poser\App\Models\User __invoke($attributes = [])
  * @method /*shortened*/|\Lukeraymonddowning\Poser\App\Models\User[]|\Lukeraymonddowning\Poser\App\Models\User create($attributes = [])
  * @method /*shortened*/|\Lukeraymonddowning\Poser\App\Models\User[]|\Lukeraymonddowning\Poser\App\Models\User make($attributes = [])
  */
class AuthorFactory extends Factory
{
    protected static $modelName = \Lukeraymonddowning\Poser\App\Models\User::class;
}
```
The model here should be `\App\Models\User`.

**It works good in a real project though.**

Do you guys have any idea how would I fix this? 

**UPD.**
Nevermind, I've fixed it by setting `App` namespace in the fake `composer.json`.

**Comment by lukeraymonddowning** [comment]
Hi @andreich1980 

How are things going with this? Everything is looking great so far 🥳👍

**Comment by andreich1980** [comment]
Thanks. I stuck trying to test that `--factory` flag calls `make:factory` command 🤔 
Trying this
```php
//        $mock = $this->partialMock(FactoryMakeCommand::class);
//        $mock->shouldReceive('handle')->once();
        $cmd = Mockery::mock('\Illuminate\Database\Console\Factories\FactoryMakeCommand[handle]');
        $cmd->shouldReceive('handle')->once();

//        $this->artisan('make:poser', ['name' => 'BookFactory', '--factory']);
        $this->artisan('make:factory', ['name' => 'AuthorFactory']);
```

And get this
```
ArgumentCountError : Too few arguments 
to function Illuminate\Console\GeneratorCommand::__construct(), 
0 passed and exactly 1 expected
```

**Comment by andreich1980** [comment]
I could commit what I have now and what works good. 
And you'll merge and close the PR. 
And when I have more time or find an idea - I'll open a new one with new tests.
Please confirm.

**Comment by lukeraymonddowning** [comment]
> I could commit what I have now and what works good.
> And you'll merge and close the PR.
> And when I have more time or find an idea - I'll open a new one with new tests.
> Please confirm.

I'd be happy with that. If all is working now we can start fresh.

**Comment by andreich1980** [comment]
Welp, that's all what I've got.

**Comment by andreich1980** [comment]
изображение

**Pull request merged**
