### PR TITLE
First pass at inline assertions

### PR DESCRIPTION
**Pull request by lukeraymonddowning**
This PR hopes to bring in a higher level of support for PhpUnit, allowing for assertions to be called inline when building up factories. It is especially useful for checks regarding database storage.

The syntax works like so:

```php
/** @test */
public function it_can_call_assertions_directly() {
    UserFactory::assertEquals('Luke Downing', 'name')(['name' => 'Luke Downing']);
}
```

This will call PhpUnit's `assertEquals` method after the `UserFactory` has created its models. As you can see, for simple tests we can just pass the model parameter we wish to test on.

Here's another example, this time with `assertCount` and a relationship:

```php
/** @test */
public function it_can_assert_counts() {
    UserFactory::withCustomers(5)->assertCount(5, 'customers')();
}
```

We can also pass a closure for more complex tests:

```php
/** @test */
public function an_untyped_function_in_the_assertion_is_passed_the_whole_collection() {
    UserFactory::times(10)->assertTrue(function($users) {
        return $users->count() == 10;
    })();
}
```

The closure will be given the created collection if you requested more than one model be constructed using the `times` method, or the single model if you're building just a single instance.

If you'd like Poser to loop through a built Collection for you in a closure, you may type hint the closure parameter, like so:

```php
/** @test */
public function collections_can_use_a_callable() {
    UserFactory::times(5)->withCustomers(5)->assertCount(5, function(User $user) {
        return $user->customers;
    })();
}
``` 

In the example above, Poser will call `assertCount` 5 times, once for each $user created, and check the assertion.

### CODE REVIEW

**Comment by lukeraymonddowning** [comment]
@andreich1980 @AlanHolmes any thoughts on this? Do you think this feature is worth adding?

Would be good to get some feedback before I go any further.

**Comment by lukeraymonddowning** [comment]
This also now works with nested relationships, like so:

```php
UserFactory::withCustomers(
            CustomerFactory::times(10)
                           ->withAttributes(['name' => 'John Doe'])
                           ->withBooks(10)
                           ->assertCount(10, 'books')
                           ->assertEquals('John Doe', 'name')
)->assertCount(10, 'customers')
 ->assertCount(10, fn($user) => $user->customers->first()->books)();
```

**Comment by lukeraymonddowning** [comment]
Simple declaration of parameters is also supported:

```php
UserFactory::new()
    ->withoutDefaults()
    ->assertEmpty('customers')
    ->assertNotNull('customers')();
```

**Comment by lukeraymonddowning** [comment]
One thing to note is that relationships cannot be asserted inline with `for<RelationshipMethodName>` uses, because the assertion will be called before the relationships are built.

**Comment by andreich1980** [comment]
Hey Luke. Cool feature. But in my opinion it looks a bit odd when you call a well known phpunit method like `assertEquals` and send 2 totally different strings as parameters. Probably this would be better `assertAttributeEquals('John', 'name')`. 
Just my opinion.

**Comment by lukeraymonddowning** [comment]
> Hey Luke. Cool feature. But in my opinion it looks a bit odd when you call a well known phpunit method like `assertEquals` and send 2 totally different strings as parameters. Probably this would be better `assertAttributeEquals('John', 'name')`. 
> 
> Just my opinion.

👍 makes sense. Under the hood it’s just calling PhpUnit methods, so can you think of any other phpunit methods that could do with the ‘Attribute’ syntax?

**Comment by andreich1980** [comment]
> ```php
> UserFactory::assertEquals('Luke Downing', 'name')(['name' => 'Luke Downing']);
> ```

This isn't readable from the first glance. `assertEquals` itself could be understood but followed with `(['name' => 'Luke Downing'])` ... 

I think that assertions should follow the object they are related to. 
`UserFactory::withAttributes(['name' => 'John'])->assertAttributeEquals('John', 'name')`

----

And what is the use case for those methods again?
What I'd normally do
```php
// Build the world
$user = UserFactory::withCustomers(5)();
$this->assertCount(5, $user->customers);

// Act: Do something, i.e. send a POST request to store a brand new Customer

// Assertions
$this->assertCount(6, $user->fresh()->customers);
```

So since I still have to call it in the traditional way in the end (`$this->assertCount`) it feels more natural for me to make the first check in the same way - so it'd be obvious for everyone (especially for me 6 month from now) what is going on here: 
1. We create a user with 5 customers
2. **Check that user has exactly 5 customers**
3. Perform the action
4. **Check that user has exactly 6 customers**

The 2 and 4 are the same steps so I'd prefer to write these in the same way `$this->assertCount`

Hope you got my point.
Thanks.

**Comment by lukeraymonddowning** [comment]
Absolutely @andreich1980, thanks for your detailed feedback. I agree with you 100%. I think this was more for simple use cases. Often, when I'm adding a column to a database table, I create a test to make sure it works as expected. In this case, my tests are usually super simple:

```php
public function it_may_have_an_expires_at_value()
{
    RentalFactory::withAttributes(['expires_at' => now()])
                           ->assertInstanceOf(Carbon::class, 'expires_at')
                           ->create();

    RentalFactory::withAttributes(['expires_at' => null])
                           ->assertNull('expires_at')
                           ->create();
}
```

One checks it casts to the correct format, the other checks it can be nullable. This is more the use case I see it used for. I would use the `$this->assertX` format for more complex tests.

My thought was that it intrinsically links the test to the factory, so you know that it is in reference to that particular factory use case.

**Comment by lukeraymonddowning** [comment]
I know this is edge case, so I'm not merging it in right away. If @AlanHolmes comes back with similar to you @andreich1980, we'll leave it out 👍 Put it to a vote.

**Comment by andreich1980** [comment]
Oh, now I understand.
I mean if you need it why not to add :)

**Comment by AlanHolmes** [comment]
I could see it being useful in some very simple tests, but not sure if I would personally use it, but that is mainly as I like to have clear distinctions between my setup/act/assert steps, but yeah I could maybe see a use for it for some pre-assertions.

I agree with @andreich1980 if you have a use for it, I see no harm in adding this.

though maybe to keep the code cleaner, should it not be moved out into a separate class?

**Pull request merged**
