### PR TITLE
`afterCreating` will now also work on related models.

### LINKED ISSUE #19: After Creating feature
Something that I have used quite heavily on the Laravel factories is the after creating functions (like `afterCreatingState`) that allow me to do certain actions after the records have been created.

It would be good if we could get something like this for Poser as well, where I could add an afterCreating closure to either the main record or any relationships.

An example of my use case is all my Users belong to a Company (one to many), but the company can have a single user marked as the main user. This is stored on the company table under `main_user_id`, and in my factory, I have a state `with_main_user` setup on the Company factory that looks like this:

```php
$factory->state(Company::class, 'with_main_user', function (Faker $faker) {
    return [];
})->afterCreatingState(Company::class, 'with_main_user', function ($company, $faker) {
    $user = factory(User::class)->create([
        'company_id' => $company->id,
    ]);

    $company->setMainUser($user);
});
```

So being able to do something like this would be pretty sweet:

```php
CompanyFactory::new()->withMainUser()->create();

// where withMainUser is a custom function in CompanyFactory

public function withMainUser($attributes = [])
{
    $this->withUsers(UserFactory::new()->afterCreating(function($user, $company) {
        $company->setMainUser($user);
    })->create(attributes));
}
```

### PR DESCRIPTION
**Pull request by lukeraymonddowning**
@AlanHolmes I've been playing with this and think we're finally there. Would you check this out before I merge it in?

### CODE REVIEW

**Comment by AlanHolmes** [comment]
Cool, I'll take a look later (or tomorrow if I dont get chance)

One thought, it would be cool if for the linked models closure it also passed the model it was linked from, in the examples case it would be user and then customer as a second param.

**Comment by lukeraymonddowning** [comment]
> One thought, it would be cool if for the linked models closure it also passed the model it was linked from, in the examples case it would be user and then customer as a second param.

Would this be infinitely deep? So if a user has customers that have books, would `afterCreating` in the book relationship receive ($book, $customer, $user)?

**Comment by AlanHolmes** [comment]
That could become a nightmare to track, but cool if possible.

But thinking about the afterCreatingState, if I was using that on a user, and then created some customers in it, then I would have user and customers, but not books (well I would on the eloquent method, depending on the order it was ran in).

And I think, from a sanity point of view that would be the easiest to replicate.

**Comment by lukeraymonddowning** [comment]
All sorted in the latest commit 👍🥳

**Comment by AlanHolmes** [comment]
🔥 This works perfectly 😀

**Pull request merged**
