### PR TITLE
Pass a collection by default

### LINKED ISSUE #84: Additional query when creating single model
Hey, I noticed that when I do this: 

```
UserFactory::new()->create();
```
there are 2 queries run
```
insert into "users" ("name", "email", "email_verified_at", "password", "remember_token", "updated_at", "created_at") values (?, ?, ?, ?, ?, ?, ?) returning "id"
```
```
select * from "users" order by "users"."id" asc limit 1000 offset 0
```

However, when I run simple `factory(User::class)->create()` there is only 1 query - the first one.
It seems this is due to this line: https://github.com/lukeraymonddowning/poser/blob/master/src/Factory.php#L248
```
$this->factory->callAfterCreating($returnFirstCollectionResultAtEnd ? $result->first() : $result);
```
I'm not fully sure what is going on there, but basically the result there is a model and not a collection, so laravel's factory builder calls `each` on the model, as if it was trying to chunk it. It might seem like a minor thing, but it adds quite a lot of additional queries which I'd like to avoid. Is there a reason as to why it is doing it, or is this a bug?

It seems like simply changing it to:
```
$this->factory->callAfterCreating($result);
```
fixes the issue, but there are no breaking tests so I am not sure what it would break 🤔

### PR DESCRIPTION
**Pull request by dsazup**
Hey, this fixes #84. Although I am not sure if this is a good change, so if you do not think this is a bug, feel free to close it.

### CODE REVIEW

**Comment by lukeraymonddowning** [comment]
Hi Friend!

Thanks for your contribution. I'm working today so will try to have a look this evening!

**Comment by lukeraymonddowning** [comment]
Just had a super quick look. I've not tried it, but I imagine this will now always return a collection?

**Comment by dsazup** [comment]
Hey, thanks for looking into it and take your time. 👍 
> Just had a super quick look. I've not tried it, but I imagine this will now always return a collection?

Afaik it does not change what is returned. It changes what is passed to `callAfterCreating` which does not return anything. Down below it still has:
```php
$this->createdInstance = $returnFirstCollectionResultAtEnd ? $result->first() : $result;

$this->testCaseCaller->processAssertions($this->createdInstance);

return $this->createdInstance;
```

**Comment by lukeraymonddowning** [comment]
Okay, just got around to testing this, and everything seems fine and dandy. Merging in 👌

**Comment by lukeraymonddowning** [comment]
@all-contributors please add @dsazup for code

**Pull request merged**
