### PR TITLE
Adds support for custom macros

### PR DESCRIPTION
**Pull request by lukeraymonddowning**
This PR adds the `Macroable` trait to the base Poser Factory class, allowing the user to define extension macro functions in a service provider (or even in the setup function of a test for smaller use cases).

As an example of a use case, the other day an issue came through where somebody was trying to use the syntax `UserFactory::items(10)->create()` instead of `UserFactory::times(10)->create()`, which obviously threw an error.

Whilst I prefer the `times` syntax, who am I to prevent users from being able to use the syntax they or their team prefer? The `Macroable` trait would allow a user to add something along the lines of `Factory::macro('items', fn($count) => static::times($count))` to their service provider and instantly gain access to the new syntax in all of their factories.

I'm sure you can imagine many other use cases.

### Concerns

My only concern with this is the fact that both `Macroable` and `Factory` implement the `__call` and `__callStatic` methods, and to my knowledge I can't call the `Macroable` magic methods from the `Factory`. Please let me know if this is in fact possible and I can update it. 

My workaround is to basically reimplement the `__call` and `__callStatic` magic method logic of `Macroable` in the Factory.

### CODE REVIEW

**Comment by lukeraymonddowning** [comment]
@AlanHolmes @andreich1980 do you have any thoughts on this, particularly the concerns?

**Comment by AlanHolmes** [comment]
I've not yet made something macroable,  but I have recently used them for
the first time in tests, and it didnt seem to have IDE completion (tho that
might have been me doing it wrong).

Another option that would allow for them to have custom methods, is them
just creating their own base factory class that extends the poser one,
which will def keep IDE completion.

A way that could make this easier for them when using the make command
would be to allow for the stub to be customised like you can in the latest
version of laravel.

Havent had chance to check your code out yet, as just quickly replying on
my phone, but thought the above was an alternative that wont have the
issues you mentioned about the magic methods

Regards
Alan Holmes

**Comment by AlanHolmes** [comment]
Oh wow, that is badly formatted when replying via email lol

**Comment by andreich1980** [comment]
I know nothing about magic of "call". And I like Alan's idea with custom base factory class that extends poser factory.

**Comment by lukeraymonddowning** [comment]
Closing this due to lack of necessity.

**Pull request closed without merging**
